# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/geowrangler2',
                'doc_host': 'https://butchtm.github.io',
                'git_url': 'https://github.com/butchtm/geowrangler2',
                'lib_path': 'geowrangler2'},
  'syms': {'geowrangler2.core': {'geowrangler2.core.foo': ('core.html#foo', 'geowrangler2/core.py')}}}
